<%@ page contentType="text/html;charset=UTF-8" language="java" %>
  <option value="">-- Please select your country --</option>
  <option value="ar">Argentina</option>
  <option value="au">Australia</option>
  <option value="at">Austria</option>
  <option value="bd">Bangladesh</option>
  <option value="by">Belarus</option>
  <option value="be">Belgium</option>
  <option value="bt">Bhutan</option>
  <option value="bo">Bolivia</option>
  <option value="ba">Bosnia and Herzegovina</option>
  <option value="br">Brazil</option>
  <option value="bn">Brunei</option>
  <option value="bg">Bulgaria</option>
  <option value="kh">Cambodia</option>
  <option value="cm">Cameroon</option>
  <option value="ca">Canada</option>
  <option value="cl">Chile</option>
  <option value="cn">China</option>
  <option value="co">Colombia</option>
  <option value="cr">Costa Rica</option>
  <option value="hr">Croatia</option>
  <option value="cu">Cuba</option>
  <option value="cy">Cyprus</option>
  <option value="cz">Czech Republic</option>
  <option value="dk">Denmark</option>
  <option value="dm">Dominica</option>
  <option value="tl">East Timor</option>
  <option value="ec">Ecuador</option>
  <option value="eg">Egypt</option>
  <option value="sv">El Salvador</option>
  <option value="ee">Estonia</option>
  <option value="fo">Faroe Islands</option>
  <option value="fj">Fiji</option>
  <option value="fi">Finland</option>
  <option value="fr">France</option>
  <option value="de">Germany</option>
  <option value="gi">Gibraltar</option>
  <option value="gr">Greece</option>
  <option value="gl">Greenland</option>
  <option value="gu">Guam</option>
  <option value="gt">Guatemala</option>
  <option value="hn">Honduras</option>
  <option value="hk">Hong Kong</option>
  <option value="hu">Hungary</option>
  <option value="is">Iceland</option>
  <option value="in">India</option>
  <option value="id">Indonesia</option>
  <option value="ie">Ireland</option>
  <option value="il">Israel</option>
  <option value="it">Italy</option>
  <option value="jm">Jamaica</option>
  <option value="jp">Japan</option>
  <option value="kz">Kazakhstan</option>
  <option value="ki">Kiribati</option>
  <option value="kp">Korea, North</option>
  <option value="kr">Korea, South</option>
  <option value="kw">Kuwait</option>
  <option value="la">Laos</option>
  <option value="lv">Latvia</option>
  <option value="lr">Liberia</option>
  <option value="ly">Libya</option>
  <option value="li">Liechtenstein</option>
  <option value="lt">Lithuania</option>
  <option value="lu">Luxembourg</option>
  <option value="mo">Macau</option>
  <option value="mk">Macedonia</option>
  <option value="my">Malaysia</option>
  <option value="mv">Maldives</option>
  <option value="ml">Mali</option>
  <option value="mt">Malta</option>
  <option value="mh">Marshall Islands</option>
  <option value="mx">Mexico</option>
  <option value="fm">Micronesia</option>
  <option value="md">Moldova</option>
  <option value="mc">Monaco</option>
  <option value="mn">Mongolia</option>
  <option value="ms">Montserrat</option>
  <option value="mm">Myanmar</option>
  <option value="nr">Nauru</option>
  <option value="np">Nepal</option>
  <option value="nl">Netherlands</option>
  <option value="an">Netherlands Antilles</option>
  <option value="nc">New Caledonia</option>
  <option value="nz">New Zealand</option>
  <option value="ng">Nigeria</option>
  <option value="nu">Niue</option>
  <option value="nf">Norfolk Island</option>
  <option value="mp">Northern Mariana Islands</option>
  <option value="no">Norway</option>
  <option value="om">Oman</option>
  <option value="pk">Pakistan</option>
  <option value="pw">Palau</option>
  <option value="pa">Panama</option>
  <option value="pg">Papua New Guinea</option>
  <option value="py">Paraguay</option>
  <option value="pe">Peru</option>
  <option value="ph">Philippines</option>
  <option value="pn">Pitcairn Island</option>
  <option value="pl">Poland</option>
  <option value="pt">Portugal</option>
  <option value="pr">Puerto Rico</option>
  <option value="qa">Qatar</option>
  <option value="re">Reunion</option>
  <option value="ro">Romania</option>
  <option value="ru">Russia</option>
  <option value="rw">Rwanda</option>
  <option value="kn">Saint Kitts &amp; Nevis</option>
  <option value="lc">Saint Lucia</option>
  <option value="vc">Saint Vincent</option>
  <option value="ws">Samoa</option>
  <option value="sm">San Marino</option>
  <option value="st">Sao Tome</option>
  <option value="sa">Saudi Arabia</option>
  <option value="sn">Senegal</option>
  <option value="sg">Singapore</option>
  <option value="sk">Slovakia</option>
  <option value="si">Slovenia</option>
  <option value="za">South Africa</option>
  <option value="es">Spain</option>
  <option value="lk">Sri Lanka</option>
  <option value="sr">Suriname</option>
  <option value="sj">Svalbard</option>
  <option value="se">Sweden</option>
  <option value="ch">Switzerland</option>
  <option value="sy">Syria</option>
  <option value="tw">Taiwan</option>
  <option value="tj">Tajikistan</option>
  <option value="th">Thailand</option>
  <option value="tk">Tokelau</option>
  <option value="to">Tonga</option>
  <option value="tt">Trinidad</option>
  <option value="tr">Turkey</option>
  <option value="tm">Turkmenistan</option>
  <option value="tc">Turks and Caicos</option>
  <option value="tv">Tuvalu</option>
  <option value="ug">Uganda</option>
  <option value="ua">Ukraine</option>
  <option value="ae">United Arab Emirates</option>
  <option value="uk">United Kingdom</option>
  <option value="us">United States</option>
  <option value="uy">Uruguay</option>
  <option value="uz">Uzbekistan</option>
  <option value="va">Vatican City</option>
  <option value="ve">Venezuela</option>
  <option value="vn">Vietnam</option>
  <option value="ot">Other Country</option>