currency.default=USD
agent.dashboard.default_page_size=100
ao.init.domain.scheme=http
app.sendmail=true
admin.domain.name=admin.dola.vn
developer.debug=true
default.cutoffperiod=14
#default.customer.unknown=unknown@mapsharing.net
#initwebs.siteurl=https://enet.io
migration.salt=startfromnowon
#Marketplace
#marketplace.json={"count":2,"items":[{"code":"MEMBO","domain":"membooking.com"},{"code":"MAPSH","domain":"mapsharing.net"}]}
#upload file folders
#dospaces.bucketName=enet
#dospaces.rootDir=product
#dospaces.secretKey=vieund+5Tl+PXismOxBfyTa/Nm/ErXk1NmV+INphKC0
#dospaces.accessKey=QWSSUJCKXAXNKDI24CS2
#dospaces.serviceEndpoint=https://sgp1.digitaloceanspaces.com
#dospaces.signingRegion=sgp1
hostmedia_filter=false
#hostmedia=https://cdn.enet.io/product
#meeting.siteurl=https://meeting.enet.io
#meeting.admin.secret=20-meeting-enet-io-22
#enetstore.siteurl=https://enet.io
#feature.land.home=nha-pho,can-ho

export.booking.header.localhost=STT;H\u1ECD v\u00E0 t\u00EAn;Nam;N\u1EEF;\u0110\u1ECBa ch\u1EC9;Ng\u01B0\u1EDDi gi\u00E1m h\u1ED9;Lo\u1EA1i vaccin;C\u00E1n b\u1ED9 ti\u00EAm;\u0110i\u1EC7n tho\u1EA1i li\u00EAn l\u1EA1c;Ghi ch\u00FA
export.booking.field.localhost=index;cusFullName;genderMale;genderFemale;cusAddress;cusRelativeName;items;cusRelativeName;cusPhone;cusRelativeName
