# This properties file is used to configure mail settings in 
# /WEB-INF/applicationContext-service.xml.

mail.default.from=dev@travelenet.com
mail.debug=false
mail.transport.protocol=smtps
mail.host=smtp.gmail.com
mail.port=465
mail.smtp.auth=true
mail.smtp.ssl.enable=false
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true

mail.userName=dev@travelenet.com
mail.password=DevTravelEnet9

mail.default.subject=Tour Admin